spring.application.name=score_gmod

server.port=3306

spring.datasource.url=mysql://root:MHBaYvgthfhcmiDoIJPKvvvyCNcqwbQC@kodama.proxy.rlwy.net:21784/railway
spring.datasource.username=root
spring.datasource.password=MHBaYvgthfhcmiDoIJPKvvvyCNcqwbQC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.session.store-type=none